version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=strong_password
      - MYSQL_DATABASE=earn
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pstrong_password"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
    
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql_data: